spring:
  application:
    name: kitchencost-api

  datasource:
    url: jdbc:postgresql://localhost:5432/kitchencost_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080